name: auto-linter

on:
  push:
    paths:
      - "*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install linter
        run: pip install ruff

      - name: Check files for linting
        run: ruff check .
