name: auto-linter

on:
  workflow_dispatch:
    

jobs:
  code:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Install linter
        run: pip install ruff

      - name: Check files for linting
        run: ruff check .
